component: scf
name: boardroom-backend

inputs:
  src: ./
  handler: server.main_handler
  runtime: Nodejs18
  region: ap-guangzhou # Cambia a tu región si es distinta (ej. ap-hongkong, ap-shanghai)
  events:
    - apigw:
        parameters:
          endpoints:
            - path: /
              method: ANY
            - path: /{proxy+} # Esto equivale al comodín /* para capturar /api/login, etc.
              method: ANY